In [1]:
# Participante: Renan D. D. Fiamoncini
# Esse código faz parte das atividades práticas que estou fazendo na Imersão Dados com Pyhton, da Alura, evento ocorrido nos dias 05 a 08 ago. 2025.
# Todos os conteúdos disponibilizados pela imersão ficam disponíveis na plataforma da Alura por tempo limitado para não assinantes da plataforma. Para rever a imersão após o prazo, é necessário ser estudante assinante da plataforma.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [5]:
# Como dá pra ver na tabela acima, o Python analisa as linhas de tabela iniciando na linha nº 0.

In [6]:
# df = dataframe

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [8]:
# Agora, com o df.info(), conseguimos ver todas as linhas e o tipo de dado de cada uma.

In [9]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [10]:
# Pq só são trazidos dados numéricos? Pq essas análises são

In [11]:
df.shape

(133349, 11)

In [12]:
# df.shape nos deu o número de linhas e de colunas do arquivo puxado pelo df

In [13]:
# df.shape não tem o parênteses após ele pois é um atributo, não é método ou função

In [14]:
# df.shape é um vetor

In [15]:
linhas, colunas = df.shape[0], df.shape[1]

In [16]:
print("Linhas:", linhas)
print("Colunas", colunas)

Linhas: 133349
Colunas 11

In [17]:
# Após declarar as variáveis 'linhas' e 'colunas', é preciso clicar no botão de play na esquerda, o de 'Executar célula', para que o print na linha seguinte possa acessá-las.

In [18]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [19]:
# Nesse momento, é comentado na aula sobre a parte de geração de código usando a I.A. do Google Gemini (associada/"embutida" ao Colab)
# Prompt pra usar: "traduza para mim todas as colunas do dataframe df para português brasileiro"

In [20]:
# Traduzindo as colunas para português brasileiro
colunas_traduzidas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

df = df.rename(columns=colunas_traduzidas)

# Exibindo as colunas traduzidas para verificar
display(df.columns)

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [21]:
# Mais adiante na aula, vimos que os nomes de colunas gerados pela I.A. não era muito práticos e voltamos para consertar.
# Por já termos mudado os nomes do inglẽs para portuguÊs anteriormente, tivemos que ir nas colunas_traduzidas e colocar dos nomes atuais para os novos.

In [22]:
# Verifiquei o prompt que me foi gerado e analisei o script gerado por conta própria e depois comparando com o gerado pelos instrutores/profs da aula.
# No final do script deles, foi gerada uma parte para que, a partir de então, fosse usada a df renomeada a partir de então. Isso foi gerado no meu um pouco diferente, mas deu certo, segue teste abaixo:

In [23]:
df.describe()

                 ano       salario            usd         remoto
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [24]:
# Para acessar uma coluna específica, usaremos:

In [25]:
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [26]:
# SE = Sênior, MI = Mid/Intermediário, EN = Entry, EX = Executivo. Depois entenderemos melhor essas siglas.

In [27]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [28]:
# FT = Fulltime, CT = Contrato Temporário, PT = Part-time, FL = Freelance

In [29]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [30]:
# Para facilitar, voltaremos no script gerado pela I.A. e ajustaremos os nomes das colunas traduzidas.

In [31]:
# Na parte de rmotos, o 0 seria totalmente presencial (0% remoto), 100 seria totalmente rmoto (100% remoto), e 50 seria híbrido (50% remoto).

In [32]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [33]:
# M = Medium, L = Large, S = Small

In [34]:
# Além de renomearmos colunas anteriormente, pode ser relevante mudar o nome das siglas para que pessoas não especialistas consigam entender mais à frente no gráfico.
# Criaremos um dicionário para a renomeação.

In [35]:
# Prompt: "traduza para portugues brasileiro as categorias da coluna 'senioridade' do dataframe DF"

In [36]:
# Dicionário para traduzir as siglas da coluna 'senioridade'
senioridade_traduzida = {
    'SE': 'Sênior',
    'MI': 'Intermediário',
    'EN': 'Iniciante',
    'EX': 'Executivo'
}

# Renomeando os valores na coluna 'senioridade'
df['senioridade'] = df['senioridade'].replace(senioridade_traduzida)

# Exibindo os valores únicos e suas contagens na coluna 'senioridade' para verificar
display(df['senioridade'].value_counts())

senioridade
Sênior           77241
Intermediário    40465
Iniciante        12443
Executivo         3200
Name: count, dtype: int64

In [37]:
# Copiei e colei o prompt da I.A. abaixo ajustando os nomes das senioridades:

In [38]:
# Dicionário para traduzir as siglas da coluna 'senioridade'
senioridade_traduzida = {
    'SE': 'Sênior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

# Renomeando os valores na coluna 'senioridade'
df['senioridade'] = df['senioridade'].replace(senioridade_traduzida)

# Exibindo os valores únicos e suas contagens na coluna 'senioridade' para verificar
display(df['senioridade'].value_counts())

senioridade
Sênior           77241
Intermediário    40465
Iniciante        12443
Executivo         3200
Name: count, dtype: int64

In [39]:
# Prompt: "traduza para portugues brasileiro as categorias da coluna 'contrato' do dataframe DF"

In [40]:
# Dicionário para traduzir as siglas da coluna 'contrato'
contrato_traduzido = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Período',
    'FL': 'Freelancer'
}

# Renomeando os valores na coluna 'contrato'
df['contrato'] = df['contrato'].replace(contrato_traduzido)

# Exibindo os valores únicos e suas contagens na coluna 'contrato' para verificar
display(df['contrato'].value_counts())

contrato
Tempo Integral    132563
Contrato             394
Meio Período         376
Freelancer            16
Name: count, dtype: int64

In [41]:
# Prompt: "traduza para portugues brasileiro as categorias da coluna 'tamanho_empresa' do dataframe DF"

In [42]:
# Dicionário para traduzir as siglas da coluna 'tamanho_empresa'
tamanho_empresa_traduzido = {
    'M': 'Média',
    'L': 'Grande',
    'S': 'Pequeno'
}

# Renomeando os valores na coluna 'tamanho_empresa'
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa_traduzido)

# Exibindo os valores únicos e suas contagens na coluna 'tamanho_empresa' para verificar
display(df['tamanho_empresa'].value_counts())

tamanho_empresa
Média      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [43]:
# Acima só troquei a tradução M = "Médio" para M = "Média"

In [44]:
# Prompt: "traduza para portugues brasileiro as categorias da coluna 'remoto' do dataframe DF"

In [45]:
# Dicionário para traduzir as categorias da coluna 'remoto'
remoto_traduzido = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

# Renomeando os valores na coluna 'remoto'
df['remoto'] = df['remoto'].replace(remoto_traduzido)

# Exibindo os valores únicos e suas contagens na coluna 'remoto' para verificar
display(df['remoto'].value_counts())

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [46]:
# Vamos agora rever como ficou tudo traduzido:

In [47]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Intermediário,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Intermediário,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [48]:
df.describe(include="object")

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Sênior,Tempo Integral,Data Scientist,USD,US,Presencial,US,Média
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [49]:
# A tabela acima dá colunas categóricas e linhas.
# 'count' é a contagem de quantos valores temos para aquela coluna.
# 'unique' são valores únicos, para cada tipo de coisa (nº de tipos de senioridades, nº de tipos de contratos, nº de tipos de cargos, etc).
# 'top' é a linha de qual informação é mais frequente para cada coluna.
# 'freq' dá quantas vezes o valor do 'top' aparece, ou seja, quantas vezes o valor mais frequente aparece em cada caso.

In [50]:
# --- DIA 2 ---


# -------------

In [51]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [52]:
# No df.isnull(), onde há dado nulo, é marcado 'true'. Onde não há dado nulo, é 'false'.

In [53]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Intermediário,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Intermediário,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [54]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [55]:
# Acima, somamos todos os nulos, foram encontrados 10 anos não preenchidos na tabela.

In [56]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [57]:
# Nan = Not a Number
# Podemos exibir linhas com o 'nan'
# Relembrando: 'df' é a nossa base

In [58]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Sênior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,Média
59692,NaN,Intermediário,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Média
59710,NaN,Iniciante,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Média
59759,NaN,Sênior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Média
59789,NaN,Sênior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,Média
131000,NaN,Sênior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Média
131006,NaN,Sênior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Média
133054,NaN,Iniciante,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Intermediário,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Intermediário,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,Grande

In [59]:
# O código acima significa que, dentro da nossa base, queremos ver tudo que tenha o isnull como true
# Ali, vemos todas as linhas da tabela com ano ausente (nan)

In [60]:
# Data science é tomar decisões com base em dados

In [61]:
# Vamos agora aprender como criar um dataframe do zero!
# Chamaremos nosso Data Frame de 'salarios' e chamaremos a biblioteca do panda (pd) para isso
# Também usaremos a biblioteca 'numpy'

In [67]:
import numpy as np

df_salarios = pd.DataFrame({
    'nome': ['Ana','Bruno','Carlos','Daniele','Val'],
    'salario': [4000,np.nan,5000,np.nan,100000]
})

# Tudo que for nulo preencheremos com a média do valor

# Calcula a média salarial e substitui os nulos pela média e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

''' Pra fazer grandes comentários, dá pra usar 3 aspas antes e depois do comentaŕio, funciona em linhas separadas
'''
# Calcula a mediana e substitui os nulos (nan) por essa mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios
# df_salarios é nossa base - salario_media é a coluna que estamos criando nela - dentro dessa base, preencheremos o 'fillna' com a média (mean) dos salários - o round(2) arredonda as casas decimais

      nome   salario  salario_media  salario_mediana
0      Ana    4000.0        4000.00           4000.0
1    Bruno       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3  Daniele       NaN       36333.33           5000.0
4      Val  100000.0      100000.00         100000.0

In [72]:
df_temperaturas = pd.DataFrame({
    "Dia": ['Segunda','Terça','Quarta','Quinta','Sexta'],
    'Temperatura': [30,np.nan,np.nan,28,27] })
# Não precisamos importar o np novamente na linha acima, já importamos anteriormente

# Usaremos o Forward Fill (ffill) abaixo para preencher as próximas casaas com o valor anterior
df_temperaturas['preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
df_temperaturas

       Dia  Temperatura  preenchido_ffill
0  Segunda         30.0              30.0
1    Terça          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [73]:
df_temperaturas = pd.DataFrame({
    "Dia": ['Segunda','Terça','Quarta','Quinta','Sexta'],
    'Temperatura': [30,np.nan,np.nan,28,27] })
# Não precisamos importar o np novamente na linha acima, já importamos anteriormente

# Usaremos o Backwards Fill (bfill) abaixo para preencher casas anteriores com o valor seguinte/posterior, é o reverso do Forwards Fill (ffill)
df_temperaturas['preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

       Dia  Temperatura  preenchido_bfill
0  Segunda         30.0              30.0
1    Terça          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [81]:
df_cidades = pd.DataFrame({
    'nome': ['Ana','Bruno','Carlos','Daniele','Val'],
    'cidade': ['São Paulo',np.nan,'Curitiba',np.nan,'Belém'] })

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informada')
df_cidades

      nome     cidade cidade_preenchida
0      Ana  São Paulo         São Paulo
1    Bruno        NaN     Não informada
2   Carlos   Curitiba          Curitiba
3  Daniele        NaN     Não informada
4      Val      Belém             Belém

In [83]:
df_limpo = df.dropna()
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [84]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025.0,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025.0,Intermediário,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025.0,Intermediário,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025.0,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média

In [ ]:
# Pq temos o ".0" nos anos, como "2025.0"?

In [85]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  float64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

In [ ]:
# Vimos acima que a variável ano é do tipo "float64" enquanto algo como salário está com "int64". Vamos converter o tipo do ano de float64 para int64

In [87]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
# Acima, colocamos o assign para que a coluna de ano receba ela mesma, mas com o tipo 'int64'
df_limpo

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Sênior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Média
1,2025,Sênior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Média
2,2025,Intermediário,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Média
3,2025,Intermediário,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Média
4,2025,Iniciante,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Média
...,...,...,...,...,...,...,...,...,...,...,...
133344,2020,Sênior,Tempo Integral,Data Scientist,412000,USD,412000,US,Remoto,US,Grande
133345,2021,Intermediário,Tempo Integral,Principal Data Scientist,151000,USD,151000,US,Remoto,US,Grande
133346,2020,Iniciante,Tempo Integral,Data Scientist,105000,USD,105000,US,Remoto,US,Pequeno
133347,2020,Iniciante,Contrato,Business Data Analyst,100000,USD,100000,US,Remoto,US,Grande
133348,2021,Sênior,Tempo Integral,Data Scientist,7000000,INR,94665,IN,Híbrido,IN,Grande